[tool.poetry]
name = "platform-for-sharing"
version = "0.1.0"
description = "Платформа для обмена вещами (бартерная система)"
authors = ["stillyc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.1.0"
django = "^5.2"
djangorestframework = "^3.16.0"
djangorestframework-simplejwt = "^5.5.0"
drf-yasg = "^1.21.10"
psycopg2-binary = "^2.9.10"
django-cors-headers = "^4.7.0"
django-filter = "^25.1"


[tool.poetry.group.dev.dependencies]
isort = "^6.0.1"
flake8 = "^7.2.0"
black = "^25.1.0"
mypy = "^1.15.0"
pillow = "^11.2.1"
ipython = "^9.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
