# Generated by Django 5.2 on 2025-04-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_for_sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeproposal",
            name="ad_receiver_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivers",
                to="platform_for_sharing.ad",
                verbose_name="на что меняем",
            ),
        ),
    ]
